{% set name = "tblite" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tblite/tblite/releases/download/v{{ version }}/tblite-{{ version }}.tar.xz
  sha256: 46d77c120501ac55ed6a64dea8778d6593b26fb0653c591f8e8c985e35884f0a

build:
  number: 1
  skip: true  # [win]

  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - meson
    - ninja
    - asciidoctor
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - libblas
    - liblapack
    - mctc-lib
    - dftd4
    - simple-dftd3
    - toml-f

test:
  requires:
    - pkg-config
  commands:
    - {{ name }} --version  # [build_platform == target_platform]
    - pkg-config {{ name }} --modversion
    - pkg-config {{ name }} --exact-version {{ version }}
    - test -f $PREFIX/include/{{ name }}.h
    - test -f $PREFIX/lib/lib{{ name }}$SHLIB_EXT

about:
  home: https://github.com/tblite/tblite
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Light-weight tight-binding framework
  doc_url: https://tblite.readthedocs.io
  dev_url: https://github.com/tblite/tblite

extra:
  recipe-maintainers:
    - awvwgk
